# This file is licensed under the terms of the MIT license https://opensource.org/license/mit
# Copyright (c) 2021-2025 Marat Reymers

# Golden config for golangci-lint

# All possible options can be found here https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml

linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 30
    # The maximal average package complexity.
    # If it's higher than 0.0 (float) the check is enabled
    # Default: 0.0
    package-average: 10.0

linters:
  disable-all: true
  enable:
    # enabled by default
    - errcheck # checking for unchecked errors, these unchecked errors can be critical bugs in some cases
    - gosimple # specializes in simplifying a code
    - govet # reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - ineffassign # detects when assignments to existing variables are not used
    - staticcheck # is a go vet on steroids, applying a ton of static analysis checks
    - typecheck # like the front-end of a Go compiler, parses and type-checks Go code

    # disabled
    # - inamedparam # [great idea, but too strict, need to ignore a lot of cases by default] reports interfaces with unnamed method parameters
    # - interfacebloat # checks the number of methods inside an interface
    # - ireturn # accept interfaces, return concrete types
    # - prealloc # [premature optimization, but can be used in some cases] finds slice declarations that could potentially be preallocated
    # - tagalign # checks that struct tags are well aligned
    # - varnamelen # [great idea, but too many false positives] checks that the length of a variable's name matches its scope
    # - wrapcheck # checks that errors returned from external packages are wrapped
    # - zerologlint # detects the wrong usage of zerolog that a user forgets to dispatch zerolog.Event

    # Disable the exhaustruct linter
  # disable:
  #   - exhaustruct

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
    # trunk-ignore(yamllint/quoted-strings)
    - source: "(noinspection|TODO)"
      linters: [godot]
    # trunk-ignore(yamllint/quoted-strings)
    - source: "//noinspection"
      linters: [gocritic]
